## DBサーバーのホスト名、指定しなければlocalhost
# データベース名
DBname: ENC[AES256_GCM,data:0PIA26fClTw=,iv:jxnz7/pXiZNx6TfT891mY4HF54uRuQT+bRNag8M15jc=,tag:wpZ9PIlRByK5tTheMyZZoA==,type:str]
# ログイン名とパスワードは環境変数で渡す
DBuser: ENC[AES256_GCM,data:cJiHDTqERw==,iv:88bFI/PXZwAO0uGSJcpJjnKoefrxj4bxrxsp8rfp6GM=,tag:PruzP0eP8lBZ6d9A3sFmJQ==,type:str]
DBpswd: ENC[AES256_GCM,data:lKHKUrNBpUryb8c=,iv:KHok1xN2wYRFvD43eMa2mVcHQj7OXgbrp35BUm03Qh0=,tag:mIiN5L5m1gas7M+D1f64xQ==,type:str]
# SSH接続を使わない
UseSSH: false
# 既存のトンネルを利用してSSH接続を使う
DBhost: 127.0.0.1
DBport: 9910
# SSH接続を使う
#UseSSH: true
#SSHhost: ${SSHHOST}
#SSHport: ${SSHPORT}
#SSHuser: ${SSHUSER}
##SSHprvkey: ${SSHKEY}
##SSHpswd: ${SSHPSWD}
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc2RQNFZDelU0b1RVMGlM
            VGFES3h4eGlaSnV6RkFqbzNLY1BKYU9NTFJZCmlFNkJaaW4vM3hFTUh0dTBldkQ2
            RGN6Tzdicmt1UjJaOFd6OWZMR25BZ28KLS0tIHdrLzZFMnZrbTNHN2p4cFVUeU9v
            bkZkbjNxdTJ6M2xHSlpKNUVOUFIyT1EKvrBMaLbsJv1mwdzPJdpmxjGIaG4wh6T9
            vpLUBmLQoUr1DE4RmhZ8SQdOanCph3Yp5cZjPo2FgtTvVG68cIO5Rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13mlf945e3emk75ys348xttw048ufq7vpgw7l94g63tl5pt03mdrsfqra2l
    encrypted_regex: ^(DBuser|DBpswd|DBname|TurnstileSiteKey|TurnstileSecretKey|IPEncryptionKeyHex)$
    lastmodified: "2026-07-23T05:50:32Z"
    mac: ENC[AES256_GCM,data:xmXe6u+h/z1sMCme5baGxfKdAhxLmJvniiTrW3+0wj58putqmmAKIqTSgoSksOeEK91xnzHFLnqQiSVNaNacZsrto/BkIOQeWcClytD9DA2GGUT/gOAJrLatSYzyvm0c/HlgKO9OSc/o5saEX+94Q5NJX+iCWgq3dS33wBxBCcs=,iv:iKJfnPailzD6xX7yVuQh7CIcRrhTaoQzgZRY0T1XDMs=,tag:FVbq9wMwotxmNul1D87Svw==,type:str]
    version: 3.13.1
